"""Defines the TarotCard class and enumerates all of the cards. Exports them
all in CARDS.
"""
import logging
from random import choice, random
from typing import Tuple

from .sentiment import Sentiment, NEGATIVE, POSITIVE, NEUTRAL
from .logs import get_logger

logger = get_logger()

INVERSE_CHANCE = .1

class TarotCard:
    __slots__ = ['name', 'keywords', 'sentiment', 'inverted']

    def __init__(self, name:str = 'Some Card',
                 keywords:Tuple[str] = ['some', 'card'],
                 sentiment:Sentiment = NEUTRAL) -> None:
        self.name = name
        self.keywords = keywords
        self.sentiment = sentiment
        self.inverted = False

    @property
    def search_term(self) -> str:
        return choice(self.keywords)

    def invert(self) -> None:
        self.inverted = not self.inverted
        self.sentiment = self.sentiment.inverse

    def __repr__(self):
        return '<TarotCard: {}>'.format(self.name)

    def __str__(self):
        return self.name

def draw_tarot_card() -> TarotCard:
    card = TarotCard(**choice(CARD_DATA))
    if random() < INVERSE_CHANCE:
        logger.debug("inverting card...")
        card.invert()

    return card


CARD_DATA = [
    # minor arcana
    # cups
    dict(name='Ace of Cups',
         sentiment=POSITIVE,
         keywords=('love', 'intimacy', 'feelings', 'compassion', 'beginning',
                   'possibility', 'relationship', 'deeper', 'romantic',
                   'friendship', 'seed', 'gift', 'opportunity', 'offer',)),
    dict(name='Two of Cups',
         sentiment=POSITIVE,
         keywords=('Partnerships', 'unions', 'energies', 'bond', 'Beauty', 'power',
                   'electric', 'vibrations', 'romance', 'sexual', 'energy',
                   'relationship', 'reconciliation', 'harmony', 'peace',)),
    dict(name='Three of Cups',
         sentiment=POSITIVE,
         keywords=('groups', 'together', 'goal', 'community', 'helping', 'caring',
                   'organizations', 'social', 'services', 'support',)),
    dict(name='Four of Cups',
         sentiment=NEUTRAL,
         keywords=('reflection', 'inaction', 'quiet', 'deliberation',
                   'contemplation', 'bad', 'undesirable', 'tribulation',
                   'sacrifice', 'meditation', 'distraction', 'direction',
                   'ignoring',)),
    dict(name='Five of Cups',
              sentiment=NEGATIVE,
              keywords=('emotional', 'dejection', 'disappointment', 'sorrow', 'failure',
                        'appreciate', 'time',)),
    dict(name='Six of Cups',
              sentiment=POSITIVE,
              keywords=('innocence', 'nostalgia', 'provincial', 'rustic', 'simple',
                        'children', 'youth', 'love',)),
    dict(name='Seven of Cups',
              sentiment=NEUTRAL,
              keywords=('cloud', 'transient', 'impractical', 'imagination', 'wishful',
                        'thinking', 'delusion', 'choice', 'temptation', 'confusion',)),
    dict(name='Eight of Cups',
              sentiment=NEGATIVE,
              keywords=('breaking', 'cracking', 'splitting', 'leaving', 'disillusion',
                        'abandon', 'abandonment',)),
    dict(name='Nine of Cups',
              sentiment=POSITIVE,
              keywords=('wish', 'fulfilled', 'fulfillment', 'goal', 'desire', 'satisfaction',
                        'satisfied', 'full', 'sated', 'smug', 'smugness', 'pleased', 'content',
                        'contentment', 'contented', 'luxurious', 'luxury',)),
    dict(name='Ten of Cups',
              sentiment=POSITIVE,
              keywords=('rainbow', 'town', 'country', 'local', 'contentment', 'content',
                        'love', 'friendship', 'friends', 'friend', 'trust', 'idyllic',
                        'ideal', 'peace',)),
    dict(name='Page of Cups',
              sentiment=POSITIVE,
              keywords=('spiritual', 'arts', 'imagination', 'psychic', 'creative',
                        'creativity', 'youth', 'party',)),
    dict(name='Knight of Cups',
              sentiment=NEUTRAL,
              keywords=('change', 'excitement', 'exciting', 'changes', 'changing',
                        'excited', 'romantic', 'romance', 'love', 'invitation',
                        'opportunity', 'offer', 'offers', 'bored', 'stimulation',
                        'boring', 'bore',)),
    dict(name='Queen of Cups',
              sentiment=POSITIVE,
              keywords=('queen', 'virtue', 'golden', 'gold', 'mother', 'friend',
                        'throne',)),
    dict(name='King of Cups',
              sentiment=POSITIVE,
              keywords=('king', 'mature', 'throne', 'sceptre', 'heart', 'love', 'music',
              'art', 'sea', 'ocean', 'aid', 'mentor', 'teacher', 'healer',
              'gentle', 'patient', 'diplomacy',)),
    # wands
    dict(name='Ace of Wands',
              sentiment=NEUTRAL,
              keywords=('creation', 'invention', 'enterprise', 'principle', 'beginning',
                        'source', 'birth', 'family', 'origin', 'virility', 'enterprises',
                        'money', 'fortune', 'inheritance', 'commencement', 'creativity',
                        'invention', 'beginning')),
    dict(name='Two of Wands',
              sentiment=NEUTRAL,
              keywords=('courage', 'daring', 'courageous', 'journey', 'journey',
                        'power', 'bold', 'boldness', 'brave', 'bravery', 'travel',)),
    dict(name='Three of Wands',
              sentiment=POSITIVE,
              keywords=('sea', 'ocean', 'journey', 'creation', 'mission', 'optimism',
              'enterprise', 'commerce', 'trade', 'achievement', 'travel',)),
    dict(name='Four of Wands',
              sentiment=POSITIVE,
              keywords=('harmony', 'positive', 'positivity', 'work', 'provincial',
              'haven', 'refuge', 'domestic', 'domesticity', 'concord',
              'harmony', 'peace', 'home', 'house', 'dwelling',)),
    dict(name='Five of Wands',
              sentiment=NEGATIVE,
              keywords=('imitation', 'play', 'sham', 'struggle', 'fight', 'tussle',
                        'combat', 'acquisition', 'struggles', 'fighting', 'fights',
                        'warfare', 'conflict', 'anxiety', 'strife',)),
    dict(name='Six of Wands',
              sentiment=POSITIVE,
              keywords=('organization', 'cleanliness', 'order', 'orderly',
                        'organizations', 'mobilization', 'success', 'triumph', 'victory',
                        'honor', 'competent', 'complete', 'completion',)),
    dict(name='Seven of Wands',
              sentiment=NEUTRAL,
              keywords=('striving', 'strive', 'protect', 'fence', 'cope', 'coping',
                        'resistance', 'resist', 'resisting', 'perseverance', 'strength',
                        'tenacity', 'courage',)),
    dict(name='Eight of Wands',
              sentiment=NEUTRAL,
              keywords=('action', 'swift', 'swiftness', 'speed', 'quick', 'quickness',
                        'journey', 'flight', 'flying', 'fly', 'motion', 'haste', 'hasty',
                        'communication', 'communicate', 'telecommunications', 'news',
                        'information', 'data',)),
    dict(name='Nine of Wands',
              sentiment=POSITIVE,
              keywords=('order', 'discipline', 'protected', 'protect', 'fence', 'wall',
              'castle', 'unassailable', 'health', 'wellbeing', 'stability',
              'tenacity', 'tenacious',)),
    dict(name='Ten of Wands',
              sentiment=NEGATIVE,
              keywords=('overload', 'overloaded', 'exhausted', 'burden', 'burdened',
                        'exhaustion', 'tired', 'overwork', 'work', 'responsibility',)),
    dict(name='Page of Wands',
              sentiment=NEUTRAL,
              keywords=('adventure', 'adventurous', 'ambition', 'ambitious',
                        'energetic', 'active', 'skill', 'skilled', 'drive', 'progress',
                        'grow', 'growth', 'move', 'moving', 'enthusiasm', 'messenger',
                        'message',)),
    dict(name='Knight of Wands',
              sentiment=POSITIVE,
              keywords=('travel', 'progress', 'traveling', 'idea', 'ideas',
                        'inventions', 'forward', 'knowledge', 'battle', 'instinct',
                        'intuition', 'creativity', 'journey',)),
    dict(name='Queen of Wands',
              sentiment=NEUTRAL,
              keywords=('queen', 'throne', 'nurture', 'nurturing', 'feminine',
                        'vivacious', 'intensity', 'fire', 'toughness', 'independence',
                        'sunflower', 'spontaneous', 'chaste', 'chastity', 'helpful',
                        'mother', 'help', 'giving', 'panther')),
    dict(name='King of Wands',
              sentiment=NEUTRAL,
              keywords=('king', 'throne', 'passion', 'mature', 'infinite', 'infinity',
                        'lion', 'salamander', 'authority', 'finances', 'money',
                        'finance', 'honesty', 'mediation', 'mediate', 'professional',
                        'fire', 'desert')),
    # pentacles
    dict(name='Ace of Pentacles',
         sentiment=POSITIVE,
         keywords=('material', 'earth', 'money', 'business', 'prosperity',
         'abundance')),
    dict(name='Two of Pentacles',
         sentiment=NEUTRAL,
         keywords=('balance', 'scale', 'juggle', 'juggling', 'juggles',
         'balancing',)),
    dict(name='Three of Pentacles',
         sentiment=POSITIVE,
         keywords=('mastery', 'perfection', 'master', 'dignity', 'power', 'skill')),
    dict(name='Four of Pentacles',
         sentiment=NEGATIVE,
         keywords=('cling', 'greed', 'keep', 'hoard', 'hoarder', 'hoarding',)),
    dict(name='Five of Pentacles',
         sentiment=NEGATIVE,
         keywords=('quagmire', 'swamp', 'trap', 'uncertain', 'struggle',
         'loss', 'insistence',)),
    dict(name='Six of Pentacles',
         sentiment=NEUTRAL,
         keywords=('giving', 'teaching', 'teach', 'information', 'secrets',
         'secret', 'leading', 'leader', 'leadership',)),
    dict(name='Seven of Pentacles',
         sentiment=NEUTRAL,
         keywords=('results', 'result', 'milestone', 'fruits', 'fruit', 'crossroads',)),
    dict(name='Eight of Pentacles',
         sentiment=NEUTRAL,
         keywords=('nitpick', 'detail', 'effort', 'absorbed', 'working',
         'diligence', 'learning',)),
    dict(name='Nine of Pentacles',
         sentiment=NEUTRAL,
         keywords=('control', 'restraint', 'isolated', 'alone', 'lone',
         'sufficient', 'leisure',)),
    dict(name='Ten of Pentacles',
         sentiment=POSITIVE,
         keywords=('abundance', 'wealth', 'wealthy', 'money', 'rich',
         'opulent', 'coffers', 'coffer', 'fortune', 'fortunes',)),
    dict(name='Page of Pentacles',
         sentiment=NEUTRAL,
         keywords=('student', 'college',)),
    dict(name='Knight of Pentacles',
         sentiment=NEUTRAL,
         keywords=('unwavering', 'grim', 'grinding', 'conservative', 'serious',
         'unreasonable',)),
    dict(name='Queen of Pentacles',
         sentiment=POSITIVE,
         keywords=('love', 'support', 'queen', 'throne', 'animals',
         'versatile', 'plants', 'green',)),
    dict(name='King of Pentacles',
         sentiment=POSITIVE,
         keywords=('successful', 'wealth', 'opportunity', 'competence', 'king',
         'throne', 'philantropy', 'firm', 'solid', 'strong',)),
    # swords
    dict(name='Ace of Swords',
         sentiment=NEUTRAL,
         keywords=('sword', 'intelligence', 'reason', 'justice', 'truth',
         'clarity', 'fortitude', 'objective', 'logic', 'reason', 'undaunted',
                   'reality')),
    dict(name='Two of Swords',
         sentiment=NEGATIVE,
         keywords=('sword', 'distress', 'ignorance', 'fear', 'terror',
         'fence',)),
    dict(name='Three of Swords',
         sentiment=NEGATIVE,
         keywords=('heartbreak', 'loneliness', 'lonely', 'disappointment',
         'disappointed', 'rejection', 'rejected', 'deserted', 'stabbed',)),
    dict(name='Four of Swords',
         sentiment=NEUTRAL,
         keywords=('break', 'rest', 'easy', 'relax', 'peace', 'quiet',
         'tranquil', 'inner',)),
    dict(name='Five of Swords',
         sentiment=NEGATIVE,
         keywords=('war', 'dishonor', 'conflict', 'fighting', 'fight', 'selfish',)),
    dict(name='Six of Swords',
         sentiment=NEUTRAL,
         keywords=('ennui', 'sadness', 'blue', 'sword', 'depression',
                   'depressed', 'listless', 'trauma', 'moving')),
    dict(name='Seven of Swords',
         sentiment=NEUTRAL,
         keywords=('running', 'wolf', 'indepdence', 'solitude', 'alone',
         'fleeing', 'secret',)),
    dict(name='Eight of Swords',
         sentiment=NEGATIVE,
         keywords=('restriction', 'confusion', 'powerless', 'trapped', 'tied',
         'restrained', 'prison', 'imprisoned',)),
    dict(name='Nine of Swords',
         sentiment=NEGATIVE,
         keywords=('worry', 'guilt', 'anguish', 'anxious', 'tense',
         'nightmare', 'insomnia', 'dark', 'sword',)),
    dict(name='Ten of Swords',
         sentiment=NEGATIVE,
         keywords=('martyr', 'dead', 'done', 'corpse', 'coffin', 'grave',
         'sacrifice', 'sacrificial', 'graveyard',)),
    dict(name='Page of Swords',
         sentiment=NEGATIVE,
         keywords=('messenger', 'sword', 'problems', 'exposed',)),
    dict(name='Knight of Swords',
         sentiment=NEUTRAL,
         keywords=('knight', 'sword', 'logic', 'rude',)),
    dict(name='Queen of Swords',
         sentiment=POSITIVE,
         keywords=('queen', 'throne', 'sword', 'humor', 'funny', 'humour',)),
    dict(name='King of Swords',
         sentiment=POSITIVE,
         keywords=('king', 'throne', 'sword', 'reason', 'research', 'library',
                   'computer', 'information', 'book', 'knowledge',)),

    # major arcana
    dict(name='The Tower',
         sentiment=NEUTRAL,
         keywords=('tower', 'explosion', 'crash', 'fire')),
    dict(name='The Star',
         sentiment=POSITIVE,
         keywords=('star', 'sun', 'stars')),
    dict(name='The Hermit',
         sentiment=NEUTRAL,
         keywords=('alone', 'hermit', 'woods', 'hut', 'inward',)),
    dict(name='The Fool',
         sentiment=NEUTRAL,
         keywords=('fool', 'new', 'carefree', 'horizon', 'journey',)),
    dict(name='The Devil',
         sentiment=NEGATIVE,
         keywords=('devil', 'devilry', 'bondage', 'hopeless', 'pain',)),
    dict(name='Temperance',
         sentiment=NEUTRAL,
         keywords=('calm', 'reflection', 'equilibrium', 'balance', 'harmony',)),
    dict(name='The Sun',
         sentiment=POSITIVE,
         keywords=('sun', 'power', 'star', 'stars', 'light', 'shine', 'warm', 'hot')),
    dict(name='The Chariot',
         sentiment=POSITIVE,
         keywords=('chariot', 'victory', 'discipline', 'soldier', 'combat',)),
    dict(name='Strength',
         sentiment=POSITIVE,
         keywords=('strong', 'muscle', 'rock', 'rocks', 'boulder', 'solid',)),
    dict(name='The High Priestess',
         sentiment=NEUTRAL,
         keywords=('priestess', 'faith', 'mystery', 'unknown',)),
    dict(name='The Moon',
         sentiment=NEUTRAL,
         keywords=('moon', 'illusion', 'fear', 'imagination', 'bewilderment',)),
    dict(name='The World',
         sentiment=POSITIVE,
         keywords=('world', 'globe', 'earth', 'satisfied', 'healing', 'achievement')),
    dict(name='The Lovers',
         sentiment=NEUTRAL,
         keywords=('love', 'heart', 'lover', 'loving', 'sex', 'sexuality',)),
    dict(name='The Magician',
         sentiment=POSITIVE,
         keywords=('magic', 'magician', 'trick', 'vitality', 'power',)),
    dict(name='The Empress',
         sentiment=NEUTRAL,
         keywords=('mother', 'empress', 'pregnant', 'nature', 'woods', 'root',)),
    dict(name='The Emperor',
         sentiment=NEUTRAL,
         keywords=('father', 'order', 'structure', 'official',)),
    dict(name='Justice',
         sentiment=NEUTRAL,
         keywords=('justice', 'law', 'scale', 'balance', 'structure', 'order',)),
    dict(name='The Hierophant',
         sentiment=NEUTRAL,
         keywords=('ruler', 'society', 'culture', 'orthodox', 'tradition', 'religion',)),
    dict(name='Judgement',
         sentiment=NEUTRAL,
         keywords=('judgement', 'punishment', 'call',)),
    dict(name='Wheel of Fortune',
         sentiment=NEUTRAL,
         keywords=('fortune', 'fate', 'fates', 'wheel',)),
    dict(name='Death',
         sentiment=NEUTRAL,
         keywords=('death', 'grave', 'graveyard', 'cemetary', 'coffin', 'skeleton', 'skeletal')),
    dict(name='The Hanged Man',
         sentiment=NEUTRAL,
         keywords=('hanging', 'martyr', 'suspended',)),
]
